version: 2
project_name: statsparrot

release:
  prerelease: auto
  draft: false

builds:
  - builder: prebuilt
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    prebuilt:
      path: binaries/{{ .Os }}_{{ .Arch }}/statsparrot
    binary: statsparrot

brews:
  - homepage: https://github.com/staticlabs/statsparrot
    description: The Parrot CLI
    name: statsparrot
    license: Apache 2.0
    url_template: https://cdn.statsparrot.com/statsparrot/{{ .Tag }}/{{ .ArtifactName }}
    repository:
      owner: staticlabs
      name: homebrew-statsparrot
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
    test: |
      system "#{bin}/statsparrot --version"
    install: |
      bin.install "statsparrot"
    commit_author:
      name: staticlabs
      email: support@statsparrot.com

archives:
  - files:
      - README.md
      - LICENSE*
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats: ["zip"]

blobs:
  - disable: "{{ .IsRelease }}"
    provider: gs
    bucket: prod-cdn.statsparrot.com
    directory: "statsparrot/nightly"
    extra_files:
      - glob: ./dist/**/*
      - glob: scripts/install.sh
  - disable: "{{ .IsNightly }}"
    provider: gs
    bucket: prod-cdn.statsparrot.com
    directory: "statsparrot/latest"
    extra_files:
      - glob: ./dist/**/*
  - disable: "{{ .IsNightly }}"
    provider: gs
    bucket: prod-cdn.statsparrot.com
    directory: "statsparrot/v{{ .Version }}"
    extra_files:
      - glob: ./dist/**/*
  - disable: "{{ .IsNightly }}"
    provider: gs
    bucket: prod-cdn.statsparrot.com
    directory: "statsparrot"
    extra_files_only: true
    extra_files:
      - glob: latest.txt
      - glob: scripts/install.sh
  - disable: "{{ .IsNightly }}"
    provider: gs
    bucket: prod-cdn.statsparrot.com
    extra_files_only: true
    extra_files:
      - glob: scripts/install.sh

changelog:
  sort: asc
  disable: "{{ .IsNightly }}"

checksum:
  name_template: checksums.txt

dockers:
  - image_templates:
      - staticlabs/statsparrot:latest
      - staticlabs/statsparrot:{{ .Tag }}
    skip_build: "{{ .IsNightly }}"
    skip_push: "{{ .IsNightly }}"
  - image_templates:
      - staticlabs/statsparrot:nightly
    skip_build: "{{ .IsRelease }}"
    skip_push: "{{ .IsRelease }}"

nightly:
  version_template: "{{ incminor .Version }}-nightly"
  publish_release: false
  keep_single_release: true
