apiVersion: v1
kind: Service
metadata:
  name: sentry-data-backend
  namespace: sentry-data
  labels:
    app.kubernetes.io/name: sentry-data
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sentry-data
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
