export const CONNECTOR_AUTH_FIELDS = {
  'Stripe':     { method: 'API Key', fields: [{ key: 'apiKey', label: 'Secret Key', type: 'password', placeholder: 'sk_live_...' }], help: 'Get keys at dashboard.stripe.com/apikeys' },
  'Shopify':    { method: 'API Key', fields: [{ key: 'shopDomain', label: 'Shop Domain', type: 'text', placeholder: 'my-store.myshopify.com' }, { key: 'apiKey', label: 'API Key', type: 'password', placeholder: 'shpat_...' }], help: 'Create custom app in Shopify Admin' },
  'WooCommerce': { method: 'API Key', fields: [{ key: 'storeUrl', label: 'Store URL', type: 'text', placeholder: 'https://store.example.com' }, { key: 'consumerKey', label: 'Consumer Key', type: 'password', placeholder: 'ck_...' }, { key: 'consumerSecret', label: 'Consumer Secret', type: 'password', placeholder: 'cs_...' }], help: 'Connect the WooCommerce REST API from WordPress' },
  'GA4':        { method: 'OAuth 2.0', fields: [{ key: 'propertyId', label: 'Property ID', type: 'text', placeholder: '123456789' }], help: 'BigQuery Data Transfer — zero code' },
  'Search Console': { method: 'OAuth 2.0', fields: [{ key: 'siteUrl', label: 'Site URL', type: 'text', placeholder: 'https://example.com' }], help: 'BigQuery Data Transfer — zero code' },
  'Google Ads': { method: 'OAuth 2.0', fields: [{ key: 'customerId', label: 'Customer ID', type: 'text', placeholder: '123-456-7890' }], help: 'BigQuery Data Transfer in GCP Console' },
  'Meta Ads': { method: 'OAuth 2.0', fields: [{ key: 'adAccountId', label: 'Ad Account ID', type: 'text', placeholder: 'act_123456789' }, { key: 'accessToken', label: 'Access Token', type: 'password', placeholder: 'EAAB...' }], help: 'Use the Meta Marketing API for metrics and audience sync' },
  'TikTok Ads': { method: 'OAuth 2.0', fields: [{ key: 'advertiserId', label: 'Advertiser ID', type: 'text', placeholder: '1234567890123456789' }, { key: 'accessToken', label: 'Access Token', type: 'password', placeholder: 'tiktok_...' }], help: 'Use the TikTok Marketing API for metrics and audience sync' },
  'HubSpot':    { method: 'API Key', fields: [{ key: 'apiKey', label: 'Private App Token', type: 'password', placeholder: 'pat-...' }], help: 'Create private app in HubSpot Settings' },
  'Salesforce': { method: 'OAuth 2.0', fields: [{ key: 'clientId', label: 'Client ID', type: 'text', placeholder: '' }, { key: 'clientSecret', label: 'Client Secret', type: 'password', placeholder: '' }, { key: 'instanceUrl', label: 'Instance URL', type: 'text', placeholder: 'https://xxx.my.salesforce.com' }], help: 'Create a connected app in Salesforce Setup' },
  'PostHog':    { method: 'API Key', fields: [{ key: 'apiKey', label: 'Personal API Key', type: 'password', placeholder: 'phx_...' }, { key: 'projectId', label: 'Project ID', type: 'text', placeholder: '12345' }], help: 'PostHog → Settings → Personal API Keys' },
  'Klaviyo':    { method: 'API Key', fields: [{ key: 'apiKey', label: 'Private API Key', type: 'password', placeholder: 'pk_...' }], help: 'Klaviyo → Settings → API Keys' },
  'Sentry':     { method: 'API Key', fields: [{ key: 'authToken', label: 'Auth Token', type: 'password', placeholder: 'sntrys_...' }, { key: 'orgSlug', label: 'Organization Slug', type: 'text', placeholder: 'my-org' }], help: 'Sentry → Settings → Auth Tokens' },
  'PostgreSQL': { method: 'Database Credentials', fields: [{ key: 'host', label: 'Host', type: 'text', placeholder: 'db.example.com' }, { key: 'port', label: 'Port', type: 'text', placeholder: '5432' }, { key: 'database', label: 'Database', type: 'text', placeholder: 'analytics' }, { key: 'username', label: 'Username', type: 'text', placeholder: 'readonly' }, { key: 'password', label: 'Password', type: 'password', placeholder: '••••••••' }], help: 'Connect a read-only PostgreSQL user' },
  'MySQL': { method: 'Database Credentials', fields: [{ key: 'host', label: 'Host', type: 'text', placeholder: 'db.example.com' }, { key: 'port', label: 'Port', type: 'text', placeholder: '3306' }, { key: 'database', label: 'Database', type: 'text', placeholder: 'analytics' }, { key: 'username', label: 'Username', type: 'text', placeholder: 'readonly' }, { key: 'password', label: 'Password', type: 'password', placeholder: '••••••••' }], help: 'Connect a read-only MySQL user' },
  'MongoDB': { method: 'Database Credentials', fields: [{ key: 'uri', label: 'Connection URI', type: 'text', placeholder: 'mongodb+srv://...' }, { key: 'database', label: 'Database', type: 'text', placeholder: 'analytics' }], help: 'Connect a read-only MongoDB URI' },
  'Prometheus': { method: 'None', fields: [{ key: 'url', label: 'Prometheus URL', type: 'text', placeholder: 'http://prometheus:9090' }], help: 'Direct Prometheus API access' },
  'BigQuery':   { method: 'Service Account', fields: [{ key: 'serviceAccountKey', label: 'Service Account JSON', type: 'textarea', placeholder: 'Paste service account key JSON' }], help: 'Create a service account with BigQuery Data Editor role' },
};

export const DEFAULT_FIELDS = { method: 'API Key', fields: [{ key: 'apiKey', label: 'API Key', type: 'password', placeholder: 'Enter key...' }], help: '' };
