import { DynamoDBDocumentClient } from '@aws-sdk/lib-dynamodb';
import { BaseRepository, Entity } from './BaseRepository';

// Representation of a Project inside a Tenant
export interface ProjectEntity extends Entity {
    tenantId: string;
    projectId: string; // Internal project ID (uuid)
    name: string;
    sourceType: 'shopify' | 'meta' | 'custom';
    status: 'active' | 'syncing' | 'processing_ai' | 'error';
    createdAt: string;

    // Configurations generated by E2B Agent meant for the Analytics Worker
    queryConfigs?: {
        widgetId: string;
        sqlString: string;
    }[];
}

export class ProjectRepository extends BaseRepository<ProjectEntity> {
    constructor(docClient: DynamoDBDocumentClient, tableName: string) {
        super(docClient, tableName);
    }

    // PK Mapping rule: TENANT#<tenantId>
    protected getPartitionKey(tenantId: string): string {
        return `TENANT#${tenantId}`;
    }

    // SK Mapping rule: PROJECT#<projectId>
    protected getSortKey(projectId?: string): string {
        if (!projectId) {
            throw new Error("projectId must be provided to determine the Sort Key for a Project.");
        }
        return `PROJECT#${projectId}`;
    }

    // Fetch a single project by its ID for a specific Tenant
    public async findOne(tenantId: string, projectId: string): Promise<ProjectEntity | null> {
        return this.get(tenantId, projectId);
    }

    // Fetch ALL projects for a specific Tenant using the SK prefix `PROJECT#`
    public async findAllForTenant(tenantId: string): Promise<ProjectEntity[]> {
        return this.queryByPrefix(tenantId, 'PROJECT#');
    }

    public async createOrUpdate(project: Omit<ProjectEntity, 'PK' | 'SK'>): Promise<void> {
        const entityToSave: ProjectEntity = {
            tenantId: project.tenantId,
            projectId: project.projectId,
            name: project.name,
            sourceType: project.sourceType,
            status: project.status,
            createdAt: project.createdAt,
            queryConfigs: project.queryConfigs,
            PK: this.getPartitionKey(project.tenantId),
            SK: this.getSortKey(project.projectId),
        };
        await this.save(entityToSave);
    }
}
