import { describe, it, expect, vi, beforeEach } from "vitest";
import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import DimensionFilter, {
  type DimensionFilterProps,
} from "./DimensionFilter";
import { DimensionFilterMode } from "../constants";

// Isolate the component from the query layer: the React hooks fetch aggregation
// rows from the Go runtime. The behaviour under test (open/close, mode commit,
// item selection, apply action routing) does not need real data.
//
// `@rilldata/web-common/lib/i18n/gen/messages` is generated by paraglide
// (`build:i18n`) and not present in a test checkout. Stub it so any message
// helper returns its own key; the tests assert on structural behavior, not text.
vi.mock("@rilldata/web-common/lib/i18n/gen/messages", () => {
  const m = new Proxy(
    {},
    {
      get: (_target, prop) => () => prop,
    },
  );
  return { m };
});

vi.mock("./useDimensionFilterValues", () => ({
  useDimensionSearchResults: vi.fn(() => ({
    data: ["alpha", "beta", "gamma"],
    error: undefined,
    isFetching: false,
  })),
  useDimensionSearchCount: vi.fn(() => ({
    data: 3,
    error: undefined,
    isFetching: false,
  })),
}));

function makeProps(overrides: Partial<DimensionFilterProps> = {}): DimensionFilterProps {
  return {
    client: {} as DimensionFilterProps["client"],
    filterData: {
      name: "country",
      label: "Country",
      mode: DimensionFilterMode.Select,
      dimensions: new Map([["mv1", { name: "country" } as never]]),
      selectedValues: ["alpha"],
      isInclude: true,
    },
    expressionMap: new Map(),
    removeDimensionFilter: vi.fn(),
    applyDimensionInListMode: vi.fn(),
    toggleDimensionValueSelections: vi.fn(),
    applyDimensionContainsMode: vi.fn(),
    toggleDimensionFilterMode: vi.fn(),
    toggleFilterPin: vi.fn(),
    toggleFilterRequired: vi.fn(),
    ...overrides,
  };
}

describe("DimensionFilter (React port)", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("renders the chip trigger and opens the menu on click", async () => {
    const user = userEvent.setup();
    render(<DimensionFilter {...makeProps()} />);

    expect(screen.getByRole("button", { name: /open country filter/i })).toBeTruthy();

    await user.click(screen.getByRole("button", { name: /open country filter/i }));

    // Menu is open: mode selector present, result rows rendered.
    expect(screen.getByLabelText("country search list")).toBeTruthy();
    expect(screen.getByLabelText("country results")).toBeTruthy();
  });

  it("commits a mode change on the controlled <select>", async () => {
    const user = userEvent.setup();
    render(<DimensionFilter {...makeProps()} />);

    await user.click(screen.getByRole("button", { name: /open country filter/i }));
    const select = screen.getByLabelText("filter_mode_select") as HTMLSelectElement;
    expect(select.value).toBe("Select");

    // Switch to InList mode.
    await user.selectOptions(select, "InList");
    expect(select.value).toBe("InList");
  });

  it("routes Apply to the InList action without double-committing", async () => {
    const user = userEvent.setup();
    const applyDimensionInListMode = vi.fn();
    const toggleDimensionFilterMode = vi.fn();
    render(
      <DimensionFilter
        {...makeProps({
          filterData: {
            name: "country",
            label: "Country",
            mode: DimensionFilterMode.InList,
            dimensions: new Map([["mv1", { name: "country" } as never]]),
            selectedValues: ["alpha"],
            isInclude: true,
          },
          // Time controls ready + a time range so the InList count query is enabled
          // and Apply is not disabled by shouldDisableApplyButton.
          timeControlsReady: true,
          timeStart: "2024-01-01T00:00:00Z",
          timeEnd: "2024-12-31T23:59:59Z",
          applyDimensionInListMode,
          toggleDimensionFilterMode,
        })}
      />,
    );

    await user.click(screen.getByRole("button", { name: /open country filter/i }));

    // Enter a value and press Enter to Apply.
    const search = screen.getByLabelText("country search list");
    await user.type(search, "alpha");
    await user.keyboard("{Enter}");

    await waitFor(() => {
      expect(applyDimensionInListMode).toHaveBeenCalled();
    });
    // No toggle-mode call unless exclude mode also changed.
    expect(toggleDimensionFilterMode).not.toHaveBeenCalled();
  });
});
