apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sentry-data
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - certificate.yaml
  - worker-cronjob.yaml
  - chat-deployment.yaml
  - chat-service.yaml
  - harness-deployment.yaml
  - harness-service.yaml
  - observer-deployment.yaml
  - observer-service.yaml
  - hpa.yaml
